// Auto-generated DAG data for HTML visualization
const DAG_DATA = [
  {
    "id": "dbrix_appinsight_to_s3",
    "summary": "把 Azure 上的 App 使用記錄搬到 AWS。",
    "schedule": "00:05 daily",
    "owner": "Jackie",
    "stability": "retries=2, delay=5s",
    "source": "Azure Blob（AppInsight Continuous Export）",
    "target": "S3 raw",
    "delay": "T+1",
    "description": "做的事：\n1. 打開 Databricks（雲端大數據工具）\n2. 同時搬 13 個 App 的資料（vLauncher、mvbA、mvbW、Teamwork、AirSync 等等）\n3. 從 Azure Blob Storage 搬到 AWS S3\n\n搬完之後通知 → **emr_v2** 可以開始處理",
    "mermaidChart": "graph TD\n  A[13 Databricks notebooks 平行] --> B[匯合] --> C[通知 emr_v2]",
    "pbiImpact": "",
    "volume": "TB 級（13 App raw log）",
    "retention": "S3 raw 全量歷史",
    "pii": "無直接 PII",
    "audience": "下游 EMR 處理用",
    "dbCoupling": "Azure Blob Storage",
    "failureReasons": "Databricks cluster 啟動失敗、Azure Blob 權限變更、跨雲網路中斷",
    "sla": "須在 00:30 前完成",
    "crossCloud": true
  },
  {
    "id": "appinsight_daily",
    "summary": "從 Azure 的 API 抓 9 個 App 的使用事件。",
    "schedule": "00:30 daily",
    "owner": "Shan",
    "stability": "retries=1, delay=5min",
    "source": "Azure AppInsight API（9 apps：Companion-prod, Display-Web, entity-insight-prod, mvbF, mvbx, myviewboard.com, myviewboard.com-v2-prod, originals-web, manager-service-prod）",
    "target": "S3 → Redshift",
    "delay": "T+1",
    "description": "做的事：\n1. 去 Azure Application Insights 打 API\n2. 一個一個抓 9 個 App 的 custom event：\n   - Companion、Display-Web、Entity Insight、mvbF、mvbx\n   - myviewboard.com、myviewboard.com-v2、Originals Web、Manager Service\n3. 每抓完一個就存到 S3 再倒進 Redshift\n\n抓完之後通知 → **7 個下游 DAG** 可以開始：\n- event_session_instance（Windows/Android/Flutter 使用時長）\n- event_session_classroom_whiteboard（教室白板）\n- event_session_companion（Companion App）\n- original_content（原創內容）\n- device_relation（裝置資料）\n- myviewboard_com（官網行為）\n- entity_insight_prod_to_insight_event_log（Insight API 事件",
    "mermaidChart": "graph TD\n  A[抓 Companion] --> B[抓 Display-Web]\n  C[抓 entity-insight] --> D[通知 insight_event_log]\n  E[抓 mvbF] --> G[匯合]\n  F[抓 mvbx] --> G\n  H[抓 myviewboard.com] --> I[抓 mvb.com-v2] --> J[抓 originals-web] --> K[抓 manager-service] --> B",
    "pbiImpact": "",
    "volume": "GB 級（9 App events）",
    "retention": "Redshift 全量歷史",
    "pii": "含 account_id、client_ip",
    "audience": "Power BI 50+ 報表源頭",
    "dbCoupling": "Azure AppInsight API",
    "failureReasons": "Azure API 限流(429)、API 格式變更、token 過期",
    "sla": "須在 01:00 前完成",
    "crossCloud": true
  },
  {
    "id": "emr_v2",
    "summary": "用 Spark 大數據引擎清洗和篩選 13 個 App 的原始資料。",
    "schedule": "00:05 daily",
    "owner": "Jackie",
    "stability": "retries=2, delay=30s",
    "source": "S3 raw (parquet from Databricks)",
    "target": "S3 processed (parquet) → Redshift",
    "delay": "T+1",
    "description": "做的事：\n1. 等 dbrix_appinsight_to_s3 搬完\n2. 檢查有沒有現成的 EMR 叢集，沒有就開一個新的\n3. 同時丟 13 個 PySpark 任務上去跑：\n   - **IFP 清洗**（vLauncher、UserGuide、SideToolBar）→ 產出 ifp_viewboard_ux_agg\n   - **Column Filter**（mvbA、mvbW、mvbW-v3、mvbA-v3、mvbF-v3）→ 篩掉不需要的欄位\n   - **Teamwork 聚合**（teamwork-prod）→ 產出 teamwork_prod_event\n   - **Launcher 彙整**（ViewBoard_OS_3.0）→ 產出 launcher3_agg\n   - **AirSync**（Sender + Receiver）→ 產出 airsync_sender/receiver_event\n   - **DM Log**（myviewboard-dm-log）→ 產出 device_session_duration\n4. 跑完各自通知下游 DAG + 把結果寫進 Redshif",
    "mermaidChart": "graph TD\n  A[等 Databricks] --> B[檢查 EMR 叢集]\n  B --> C{叢集存在?}\n  C -->|No| D[建立新叢集]\n  C -->|Yes| E[取得叢集資訊]\n  D --> E\n  E --> F[13 個 App 平行處理]\n  F --> G[IFP 清洗 x3]\n  F --> H[Column Filter x5]\n  F --> I[Teamwork 聚合]\n  F --> J[Launcher/AirSync/DM]",
    "pbiImpact": "~10 reports: vlauncher, AirSync, EDLA, IFP Activity 等",
    "volume": "TB 級（13 App Spark）",
    "retention": "S3 processed 全量",
    "pii": "含 account_id",
    "audience": "下游 Session DAG + Redshift",
    "dbCoupling": "無外部 DB",
    "failureReasons": "EMR cluster 啟動失敗、Spark OOM、S3 逾時",
    "sla": "須在 01:00 前完成",
    "crossCloud": false
  },
  {
    "id": "event_session_instance",
    "summary": "算出每個使用者在 myViewBoard 上用了多久（Session 切割）。",
    "schedule": "00:30 daily",
    "owner": "Vance",
    "stability": "retries=3, delay=5min",
    "source": "",
    "target": "operation_session_windows, operation_session_android, operation_session_flutter, device_session_duration, operation_event_windows_two_year_lower",
    "delay": "T+1",
    "description": "做的事：\n1. 等兩件事完成：appinsight_daily 抓完 + emr_v2 篩選完\n2. 按平台分別計算 Session：\n   - Android 版 → operation_session_android\n   - Windows 版 → operation_session_windows\n   - Flutter 版 → operation_session_flutter\n3. 規則：超過 30 分鐘沒動作 = 新的 Session\n4. 算出每台裝置的使用時長 → device_session_duration\n5. 每個月 8 號之後，額外跑一次 Canvas Hour 聚合（月報用）\n\n算完通知 → **dags_dbt_instance** 開始做資料模型轉",
    "mermaidChart": "graph TD\n  A[等 appinsight] --> D[Flutter filter]\n  B[等 EMR mvbA] --> E[匯合]\n  C[等 EMR mvbW] --> E\n  E --> F[Android Session]\n  F --> G[Windows Session]\n  D --> H[Flutter Session]\n  G --> I[通知 dbt_instance]\n  H --> I\n  I --> J{每月8號後?}\n  J -->|Yes| K[Canvas Hour]\n  J -->|No| L[結束]",
    "pbiImpact": "~25 reports: Canvas Analysis, Instance Snapshot, Weekly Snapshot, Entity Canvas Activity, All Service Snapshot 等",
    "volume": "GB 級（百萬筆→session）",
    "retention": "operation_session 每日追加、two_year_lower 保留兩年",
    "pii": "含 account_id、instance_id、country",
    "audience": "Power BI 25+ 報表",
    "dbCoupling": "無",
    "failureReasons": "上游 appinsight/emr 延遲、Redshift COPY 失敗",
    "sla": "須在 02:00 前完成",
    "crossCloud": false
  },
  {
    "id": "event_session_instance_v3",
    "summary": "跟上面一樣，但是算 V3 新版 App 的使用時長。",
    "schedule": "00:30 daily",
    "owner": "Jackie",
    "stability": "retries=3, delay=5min",
    "source": "",
    "target": "operation_session_windows_v3, operation_session_android_v3, operation_session_flutter_v3",
    "delay": "T+1",
    "description": "做的事：\n1. 等 emr_v2 處理完 v3 版的 mvbA、mvbW、mvbF\n2. 依序計算 Windows v3 → Android v3 → Flutter v3 的 Session\n3. 通知 dags_dbt_instanc",
    "mermaidChart": "graph TD\n  A[等 EMR mvbA-v3] --> D[匯合]\n  B[等 EMR mvbW-v3] --> D\n  C[等 EMR mvbF-v3] --> D\n  D --> E[Windows v3 Session]\n  E --> F[Android v3 Session]\n  F --> G[Flutter v3 Session]\n  G --> H[通知 dbt_instance]",
    "pbiImpact": "",
    "volume": "GB 級",
    "retention": "每日追加",
    "pii": "含 account_id、instance_id",
    "audience": "Power BI（3.0 系列）",
    "dbCoupling": "無",
    "failureReasons": "上游 emr_v2 延遲",
    "sla": "須在 02:00 前完成",
    "crossCloud": false
  },
  {
    "id": "event_session_classroom_whiteboard",
    "summary": "算教室白板的使用時長。",
    "schedule": "00:30 daily",
    "owner": "Shan",
    "stability": "retries=1, delay=5min",
    "source": "",
    "target": "operation_session_classroom, operation_session_whiteboard",
    "delay": "T+1",
    "description": "做的事：\n1. 等 appinsight_daily 抓完 mvbx 的資料\n2. 先算 Whiteboard 的 Session\n3. 再算 Classroom 的 Sessio",
    "mermaidChart": "graph TD\n  A[等 appinsight mvbx] --> B[Whiteboard Session] --> C[Classroom Session]",
    "pbiImpact": "",
    "volume": "GB 級",
    "retention": "每日追加",
    "pii": "含 account_id",
    "audience": "Power BI（Classroom/WB 報表）",
    "dbCoupling": "無",
    "failureReasons": "上游 appinsight 延遲",
    "sla": "須在 02:00 前完成",
    "crossCloud": false
  },
  {
    "id": "event_session_companion",
    "summary": "算 Companion App 的使用紀錄。",
    "schedule": "00:30 daily",
    "owner": "Shan",
    "stability": "retries=1, delay=5min",
    "source": "",
    "target": "datamart_companion.companion_session_*",
    "delay": "T+1",
    "description": "做的事：\n1. 等 appinsight_daily 抓完\n2. 算 Companion 的 Session\n3. 算 Companion 的功能使用統計\n4. 彙整 Companion App 資",
    "mermaidChart": "graph TD\n  A[等 appinsight Companion] --> B[Companion Session] --> C[功能使用統計] --> D[App 資訊彙整]",
    "pbiImpact": "~6 reports: Companion Snapshot, Whiteboard and Companion Analysis 等",
    "volume": "GB 級",
    "retention": "每日追加",
    "pii": "含 account_id",
    "audience": "Power BI 6 報表",
    "dbCoupling": "無",
    "failureReasons": "上游 appinsight 延遲",
    "sla": "須在 02:00 前完成",
    "crossCloud": false
  },
  {
    "id": "original_content",
    "summary": "統計原創內容（OC）在各平台的使用情況。",
    "schedule": "00:30 daily",
    "owner": "Shan",
    "stability": "retries=3, delay=5min",
    "source": "",
    "target": "datamart_oc.oc_*",
    "delay": "T+1",
    "description": "做的事：\n1. 等 appinsight_daily + emr_v2 都完成\n2. 更新 OC 對照表\n3. 同時抓 5 個平台的 OC 使用資料：Windows、Android、Flutter、Classroom、Whiteboard\n4. 另外處理 OC 遊戲資料 + OC 資源清單 + 網頁版 O",
    "mermaidChart": "graph TD\n  A[更新 OC 對照表] --> B[等 appinsight 完成]\n  A --> C[等 EMR mvbA]\n  A --> D[等 EMR mvbW]\n  B --> E[Flutter OC]\n  B --> F[Classroom OC]\n  B --> G[Whiteboard OC]\n  B --> H[OC 遊戲] --> I[OC 資源] --> J[網頁版 OC]\n  C --> K[Android OC]\n  A --> K\n  D --> L[Windows OC]\n  A --> L\n  style A fill:#FFF9C4\n  style B fill:#E3F2FD\n  style C fill:#E3F2FD\n  style D fill:#E3F2FD",
    "pbiImpact": "~7 reports: OC Usage/Site/Analysis 等",
    "volume": "GB 級",
    "retention": "每日追加",
    "pii": "含 account_id、content_id",
    "audience": "Power BI 7 報表",
    "dbCoupling": "無",
    "failureReasons": "上游 appinsight/emr 延遲",
    "sla": "須在 02:00 前完成",
    "crossCloud": false
  },
  {
    "id": "myviewboard_com",
    "summary": "統計 myviewboard.com 官網上使用者的點擊行為。",
    "schedule": "00:30 daily",
    "owner": "Jackie",
    "stability": "retries=3, delay=5min",
    "source": "",
    "target": "myviewboard_com_tiles_click, myviewboard_com_2",
    "delay": "T+1",
    "description": "做的事：\n1. 等 appinsight_daily 抓完 myviewboard.com 的兩組資料\n2. 分支 1：處理舊版官網的 tiles 點擊事件\n3. 分支 2：處理新版官網的互動事",
    "mermaidChart": "graph TD\n  A[等 myviewboard.com 資料] --> B[tiles 點擊事件]\n  C[等 mvb.com-v2 資料] --> D[新版互動事件]",
    "pbiImpact": "~8 reports: Web Tool Usage, Landing Page, Site Snapshot 等",
    "volume": "MB 級",
    "retention": "每日追加",
    "pii": "含 client_ip、session_id",
    "audience": "Power BI 8 報表",
    "dbCoupling": "無",
    "failureReasons": "上游 appinsight 延遲",
    "sla": "須在 01:30 前完成",
    "crossCloud": false
  },
  {
    "id": "entity_insight_prod_to_insight_event_log",
    "summary": "抓 Entity Insight API 自身的使用事件，存到 Redshift。",
    "schedule": "00:30 daily",
    "owner": "Jackie",
    "stability": "retries=3, delay=10min",
    "source": "",
    "target": "insight_event_count_all_time_v",
    "delay": "T+1",
    "description": "做的事：\n1. 等 appinsight_daily 抓完 entity-insight-prod 的資料\n2. 清洗後寫入 Redshift 的 insight_event_count_all_time_",
    "mermaidChart": "graph TD\n  A[等 appinsight entity-insight] --> B[清洗 event log] --> C[寫入 Redshift]",
    "pbiImpact": "",
    "volume": "MB 級",
    "retention": "全量歷史",
    "pii": "含 account_id、entity_id",
    "audience": "Power BI（Insights Snapshot）",
    "dbCoupling": "無",
    "failureReasons": "上游 appinsight 延遲",
    "sla": "須在 01:30 前完成",
    "crossCloud": false
  },
  {
    "id": "entity_account",
    "summary": "從產品資料庫抓帳號、Entity、登入記錄，建立用戶基本資料。",
    "schedule": "00:00 daily",
    "owner": "Shan",
    "stability": "retries=22, delay=30min ⚠️ 極不穩定",
    "source": "Product PG（account, entity, login_log）",
    "target": "S3 → Redshift",
    "delay": "T+1",
    "description": "這是最不穩定的 DAG（retries=22，最多重試 11 小時）。\n\n做的事：\n1. **同時做兩件事：**\n   - 路線 A：抓 Entity 帳號綁定紀錄 → 抓已刪除帳號\n   - 路線 B：產生地區名稱對照表 → 抓 Entity 地理位置（會打 IP 地理位置 API、判斷 K12/大學）\n2. 等兩條路線都完成\n3. **同時抓兩種登入記錄：**\n   - 網頁版登入（web_log）\n   - App 版登入（app_log）\n4. 等兩邊都抓完，合併成一份\n5. **最後分兩條路產出：**\n   - 路線 A：account_login_count（登入次數統計）→ 通知 dbt_users\n   - 路線 B：account_fixed（帳號基本資料：角色、地區、教育程度、是否學生）→ 通知 dbt_user",
    "mermaidChart": "graph TD\n  A[抓 Entity 綁定] --> C[抓已刪除帳號]\n  B[產生地區對照] --> D[抓 Entity 地理位置]\n  C --> E[匯合1]\n  D --> E\n  E --> F[抓網頁登入]\n  E --> G[抓App登入]\n  F --> H[合併]\n  G --> H\n  H --> I[登入次數統計]\n  H --> J[帳號基本資料]\n  I --> K[通知 dbt_users]\n  J --> K",
    "pbiImpact": "~22 reports: User Snapshot, Entity Snapshot, Global Sales Snapshot, Entity Segmentation 等",
    "volume": "GB 級（帳號+Entity+登入）",
    "retention": "account_fixed 全量刷新、login_count 每日追加",
    "pii": "⚠️ 高敏感：email, name, IP",
    "audience": "Power BI 22+ 報表 + dbt_users",
    "dbCoupling": "⚠️ Product PG — schema 改動直接壞",
    "failureReasons": "PG PITR recovery 衝突、IP API 不穩、分頁查詢逾時",
    "sla": "常因 retries=22 延遲到 03:00+",
    "crossCloud": false
  },
  {
    "id": "viewsonic_migration",
    "summary": "從 ViewSonic Account 資料庫抓帳號、SSO、Entity 資料搬到 Redshift。",
    "schedule": "00:00 daily",
    "owner": "Vance",
    "stability": "retries=3, delay=5min",
    "source": "VS Account PG（account, entity, sso, role）",
    "target": "S3 → Redshift",
    "delay": "T+1",
    "description": "做的事：\n1. 依序抓多張帳號相關表（account、account_mfa、account_role、account_sso 等）\n2. 抓 Entity 相關表（entity、entity_request、invite_entity_request）\n3. 抓登入記錄（login_log）\n4. 完成後通知 → dbt_user",
    "mermaidChart": "graph TD\n  A[event_store_db] --> B[account 表] --> C[log 表] --> D[entity 表] --> E[通知 dbt_users]",
    "pbiImpact": "",
    "volume": "MB 級",
    "retention": "全量刷新",
    "pii": "⚠️ 高敏感：email, SSO",
    "audience": "dbt_users → Power BI",
    "dbCoupling": "⚠️ VS Account PG",
    "failureReasons": "DB 連線逾時、VPC peering",
    "sla": "須在 01:00 前完成",
    "crossCloud": false
  },
  {
    "id": "instance_relation",
    "summary": "抓裝置註冊資訊和登入記錄，建立裝置 → Entity → 帳號的對應關係。",
    "schedule": "00:20 daily",
    "owner": "Jackie",
    "stability": "retries=3, delay=10min",
    "source": "Product PG（instance_info, login_log）",
    "target": "S3 → Redshift",
    "delay": "T+1",
    "description": "做的事：\n1. 等 instance_android_launcher_device_entity 完成\n2. 抓裝置修改記錄 → 通知 dbt_instance\n3. 抓多筆裝置登入 log\n4. 建立 instance_entity_account 對應表 → 通知 dbt_instanc",
    "mermaidChart": "graph TD\n  A[等 Android launcher] --> B[抓裝置修改記錄]\n  B --> C[通知 dbt_instance]\n  B --> D[抓登入 log]\n  D --> E[建立 instance_entity_account]\n  E --> F[通知 dbt_instance]",
    "pbiImpact": "",
    "volume": "GB 級",
    "retention": "instance_info_all_time 全量、其他每日追加",
    "pii": "含 account_id、instance_id",
    "audience": "Power BI 14+ 報表 + dbt_instance",
    "dbCoupling": "⚠️ Product PG",
    "failureReasons": "上游 android_launcher 延遲、PG 連線不穩",
    "sla": "須在 01:30 前完成",
    "crossCloud": false
  },
  {
    "id": "instance_android_launcher_device_entity",
    "summary": "從 DM 資料庫抓 Android Launcher 的裝置、帳號綁定資料。",
    "schedule": "00:20 daily",
    "owner": "Jackie",
    "stability": "retries=9, delay=6min ⚠️ 不穩定",
    "source": "DM PG（launcher_device_entity）",
    "target": "S3 → Redshift",
    "delay": "T+1",
    "description": "做的事：\n1. 同時抓 3 張表：instance_android、android_launcher、launcher_device_entity\n2. 等全部完成後通知 → instance_relatio",
    "mermaidChart": "graph TD\n  A[instance_android] --> D[匯合]\n  B[android_launcher] --> D\n  C[launcher_device_entity] --> D\n  D --> E[通知 instance_relation]",
    "pbiImpact": "",
    "volume": "MB 級",
    "retention": "全量刷新",
    "pii": "含 account_id、device_id",
    "audience": "instance_relation 下游",
    "dbCoupling": "⚠️ DM PG",
    "failureReasons": "DM DB 連線逾時（retries=9）",
    "sla": "須在 00:50 前完成",
    "crossCloud": false
  },
  {
    "id": "device_relation",
    "summary": "從 Device Manager 資料庫抓裝置基本資料（型號、MAC、使用紀錄）。",
    "schedule": "00:30 daily",
    "owner": "Shan",
    "stability": "retries=1, delay=5min",
    "source": "DM PG（device_info_raw, usage_log, mac, app_action_log） + AppInsight",
    "target": "S3 → Redshift",
    "delay": "T+1",
    "description": "做的事：\n1. 等 appinsight_daily 完成\n2. 依序抓：app_action_log → api_request_log → device_info → device_usage\n3. 另外平行抓：launch_country_log、device_mac、broadcast 資",
    "mermaidChart": "graph TD\n  A[等 appinsight] --> B[app_action_log]\n  B --> C[api_request_log]\n  C --> D[device_info]\n  D --> E[device_usage]\n  F[launch_country_log] --> G[device_mac]\n  H[broadcast 資料]",
    "pbiImpact": "~14 reports: Device Manager Snapshot/Usage, Entity Launched Device Trend 等",
    "volume": "GB 級",
    "retention": "每日追加",
    "pii": "含 device_id、MAC、account_id",
    "audience": "Power BI 14+ 報表",
    "dbCoupling": "⚠️ DM PG + AppInsight API",
    "failureReasons": "DM DB 不穩、AppInsight 延遲",
    "sla": "須在 02:00 前完成",
    "crossCloud": true
  },
  {
    "id": "subscription",
    "summary": "從產品 DB 抓訂閱資料（誰訂了什麼方案、到期日）。",
    "schedule": "00:10 daily",
    "owner": "Shan",
    "stability": "retries=1, delay=10min",
    "source": "Product PG（entity_subscription, service_instance, user_subscription）",
    "target": "S3 → Redshift",
    "delay": "T+1",
    "description": "做的事（依序）：\n1. entity_subscription（Entity 級訂閱）\n2. service_instance（服務綁定裝置）\n3. user_subscription（個人訂閱）\n4. feature_label_list（功能標籤",
    "mermaidChart": "graph TD\n  A[entity_subscription] --> B[service_instance] --> C[user_subscription] --> D[feature_label_list]",
    "pbiImpact": "~10 reports: Entity Subscription, Premium Feature, Manager Monetization 等",
    "volume": "MB 級",
    "retention": "全量+每日混合",
    "pii": "含 account_id、entity_id",
    "audience": "Power BI 10+ 報表",
    "dbCoupling": "⚠️ Product PG",
    "failureReasons": "PG 連線不穩",
    "sla": "須在 00:30 前完成",
    "crossCloud": false
  },
  {
    "id": "teamwork",
    "summary": "從 Teamwork 資料庫抓協作活動資料。",
    "schedule": "00:05 daily",
    "owner": "Jackie",
    "stability": "retries=3, delay=5min",
    "source": "Teamwork PG（board, project, event, mvb_id_relation）",
    "target": "S3 → Redshift",
    "delay": "T+1",
    "description": "做的事：\n1. 等 emr_v2 處理完 teamwork_prod\n2. 更新 app 名稱對照 → 處理事件資料\n3. 同時抓多組資料：ID 關聯表、維度表（board, project, team）、事件 lo",
    "mermaidChart": "graph TD\n  A[等 EMR teamwork] --> B[更新 app 對照]\n  B --> C[事件資料]\n  D[ID 關聯表]\n  E[維度表: board/project/team]\n  F[事件 log]",
    "pbiImpact": "~8 reports: TeamOne Beta 系列",
    "volume": "GB 級",
    "retention": "board/project 全量、event 每日",
    "pii": "含 account_id",
    "audience": "Power BI 8 報表",
    "dbCoupling": "⚠️ Teamwork PG",
    "failureReasons": "上游 emr 延遲、TW PG 不穩",
    "sla": "須在 01:30 前完成",
    "crossCloud": false
  },
  {
    "id": "salesforce",
    "summary": "從 Salesforce CRM 抓銷售 Entity 關係。",
    "schedule": "00:30 daily",
    "owner": "Jackie",
    "stability": "retries=3, delay=5min",
    "source": "Salesforce API（entity_sales_relation）",
    "target": "S3 → Redshift",
    "delay": "T+1",
    "description": "做的事（單一步驟）：\n1. 抓 entity_sales_relation 寫入 Redshif",
    "mermaidChart": "graph TD\n  A[抓 entity_sales_relation] --> B[寫入 Redshift]",
    "pbiImpact": "~15 reports: sales 系列, Global Sales Snapshot, MSP 系列, Manager Monetization 等",
    "volume": "MB 級",
    "retention": "全量刷新",
    "pii": "⚠️ 含 contact_email、company_name",
    "audience": "Power BI 15 報表",
    "dbCoupling": "Salesforce API",
    "failureReasons": "API 限流、token 過期",
    "sla": "須在 01:30 前完成",
    "crossCloud": false
  },
  {
    "id": "email_campaign",
    "summary": "抓 Email 行銷活動的發送紀錄和點擊紀錄。",
    "schedule": "01:15 daily",
    "owner": "Arthur",
    "stability": "retries=1, delay=2min",
    "source": "Email Service PG + DynamoDB",
    "target": "S3 → Redshift",
    "delay": "T+1",
    "description": "做的事（依序）：\n1. 抓行銷活動操作記錄\n2. 抓 email template\n3. 抓目標用戶清單\n4. 從 DynamoDB 抓發送記錄\n5. 抓點擊事件 URL\n6. 從 Email Service PG 抓 campaign / group / tag",
    "mermaidChart": "graph TD\n  A[campaign 操作] --> B[template] --> C[目標用戶] --> D[DynamoDB 發送記錄] --> E[點擊事件] --> F[PG campaign] --> G[PG group] --> H[PG tags]",
    "pbiImpact": "",
    "volume": "MB 級",
    "retention": "每日追加",
    "pii": "⚠️ 含 email、account_id",
    "audience": "Power BI + DiPS",
    "dbCoupling": "⚠️ Email Service PG + DynamoDB",
    "failureReasons": "DynamoDB 逾時、Email PG 不穩",
    "sla": "須在 02:00 前完成",
    "crossCloud": false
  },
  {
    "id": "account_related",
    "summary": "抓帳號角色、登入次數、問卷資料。",
    "schedule": "00:30 daily",
    "owner": "Shan",
    "stability": "retries=2, delay=30min",
    "source": "Product PG（user_account_role, login, survey）",
    "target": "S3 → Redshift",
    "delay": "T+1",
    "description": "做的事（依序）：\n1. user_account_role（帳號角色）\n2. insight_survey（問卷）\n3. login 相關統",
    "mermaidChart": "graph TD\n  A[user_account_role] --> B[insight_survey] --> C[login 統計]",
    "pbiImpact": "",
    "volume": "MB 級",
    "retention": "每日追加",
    "pii": "⚠️ 含 account_id、login IP",
    "audience": "Power BI 5 報表",
    "dbCoupling": "⚠️ Product PG",
    "failureReasons": "PG 連線不穩",
    "sla": "無嚴格 SLA",
    "crossCloud": false
  },
  {
    "id": "community",
    "summary": "從 Bettermode 社群平台抓會員和貼文資料。",
    "schedule": "00:00 daily",
    "owner": "Vance",
    "stability": "retries=1, delay=1min",
    "source": "Bettermode GraphQL API",
    "target": "S3 → Redshift",
    "delay": "T+1",
    "description": "做的事（三個同時跑）：\n1. 抓會員列表（GraphQL API）\n2. 抓貼文列表\n3. 抓教師徽章資",
    "mermaidChart": "graph TD\n  A[抓會員列表]\n  B[抓貼文列表]\n  C[抓教師徽章]",
    "pbiImpact": "",
    "volume": "MB 級",
    "retention": "全量刷新",
    "pii": "含 member_id",
    "audience": "Power BI（Community Analysis）",
    "dbCoupling": "Bettermode GraphQL API",
    "failureReasons": "API 格式變更、rate limit",
    "sla": "無嚴格 SLA",
    "crossCloud": false
  },
  {
    "id": "dags_dbt_instance",
    "summary": "等裝置和 Session 資料都準備好，再跑 dbt 模型產出分析用的表。",
    "schedule": "00:20 daily",
    "owner": "Vance",
    "stability": "retries=1, delay=5min",
    "source": "",
    "target": "instance_android_launcher_device_entity_all_time, instance_entity_account_all, instance_location_all_time（+deps）, operation_event_windows_two_year_lower",
    "delay": "T+1",
    "description": "做的事：\n1. 等 4 個信號（可能來自不同 DAG、不同時間完成）：\n   - instance_relation 的 instance_entity_account 完成\n   - instance_relation 的 instance_registered_fixed 完成\n   - event_session_instance v2 完成\n   - event_session_instance v3 完成\n2. 收到信號後跑 4 個 dbt model：\n   - instance_android_launcher_device_entity_all_time\n   - instance_entity_account_all\n   - instance_location_all_time（含上游依賴一起跑）\n   - operation_event_windows_two_year_lowe",
    "mermaidChart": "graph TD\n  S1[等 instance_entity_account] --> M1[dbt: instance_android_launcher_all_time]\n  S1 --> M2[dbt: instance_entity_account_all]\n  S2[等 instance_registered_fixed] --> M3[dbt: instance_location_all_time]\n  S3[等 session v2] --> M3\n  S4[等 session v3] --> M3\n  S3 --> M4[dbt: operation_event_windows_two_year]\n  style S1 fill:#E3F2FD\n  style S2 fill:#E3F2FD\n  style S3 fill:#E3F2FD\n  style S4 fill:#E3F2FD\n  style M1 fill:#FFE6CC\n  style M2 fill:#FFE6CC\n  style M3 fill:#FFE6CC\n  style M4 fill:#FFE6CC",
    "pbiImpact": "",
    "volume": "GB 級（RS 內部）",
    "retention": "_all_time 全量歷史",
    "pii": "含 account_id、instance_id",
    "audience": "Power BI datamart view",
    "dbCoupling": "無（RS 內部）",
    "failureReasons": "上游 3 DAG 延遲、dbt 語法錯誤",
    "sla": "須在 03:00 前完成",
    "crossCloud": false
  },
  {
    "id": "dags_dbt_users",
    "summary": "等帳號資料準備好，再跑 dbt 模型產出用戶分析表。",
    "schedule": "00:00 daily",
    "owner": "Vance",
    "stability": "retries=1, delay=5min",
    "source": "",
    "target": "user_entity_country_all_time（+deps）, mvb_id_chosen_country",
    "delay": "T+1",
    "description": "做的事：\n1. 等 3 個信號：\n   - entity_account 的 account_login_count 完成\n   - entity_account 的 account_fixed 完成\n   - viewsonic_migration 的 event_store_db 完成\n2. 跑 2 個 dbt model：\n   - user_entity_country_all_time（含上游依賴）\n   - mvb_id_chosen_countr",
    "mermaidChart": "graph TD\n  A[等 account_login_count] --> D[dbt run]\n  B[等 account_fixed] --> D\n  C[等 event_store_db] --> D\n  D --> E[user_entity_country_all_time]\n  D --> F[mvb_id_chosen_country]",
    "pbiImpact": "",
    "volume": "GB 級（RS 內部）",
    "retention": "_all_time 全量歷史",
    "pii": "含 account_id、country",
    "audience": "Power BI datamart view",
    "dbCoupling": "無（RS 內部）",
    "failureReasons": "上游 entity_account 延遲（retries=22）",
    "sla": "須在 03:00 前完成",
    "crossCloud": false
  },
  {
    "id": "entity_insight_migration",
    "summary": "從 Redshift 搬 28 張表到產品資料庫，供 Entity Insight 網站使用。",
    "schedule": "03:00 daily",
    "owner": "Vance",
    "stability": "retries=1, delay=5min",
    "source": "",
    "target": "Savvy PostgreSQL（savvy.*）+ daco PostgreSQL（daco.entity_account）",
    "delay": "T+1",
    "description": "做的事：\n1. 一張一張循序處理 28 張表（不是同時，怕資料庫扛不住）\n2. 每張表的流程：查 Redshift → 存 CSV 到 S3 → 從 S3 載入 Savvy PG\n3. 三種載入方式：\n   - **全量刷新（4 張表）**：先刪光再全部重新倒入（例如：裝置狀態、職業對照）\n   - **滾動 90 天（13 張表）**：每天加新的、刪掉 90 天前的舊資料\n   - **每日追加（11 張表）**：只處理今天的資料\n4. 全部完成後通知 → email_alert_lis",
    "mermaidChart": "graph TD\n  A[28 張表循序執行] --> B[查 Redshift]\n  B --> C[存 CSV 到 S3]\n  C --> D[載入 Savvy PG]\n  D --> E{該表的策略}\n  E -->|Snapshot 4表| F[刪光→全量寫入]\n  E -->|Rolling90 13表| G[刪今天+90天前→寫今天]\n  E -->|Daily 11表| H[刪今天→寫今天]\n  F --> I[下一張表]\n  G --> I\n  H --> I\n  I -->|重複28次| B\n  I -->|全部完成| J[通知 email_alert_list]\n  style F fill:#FFCDD2\n  style G fill:#FFF9C4\n  style H fill:#C8E6C9",
    "pbiImpact": "",
    "volume": "GB 級（28 表 RS→PG）",
    "retention": "Snapshot 4表/Rolling90 13表/Daily 11表",
    "pii": "⚠️ 含帳號/Entity/裝置完整資料",
    "audience": "Entity Insight API → 前端 Dashboard",
    "dbCoupling": "⚠️ Savvy PG = 產品 write endpoint",
    "failureReasons": "RS 查詢逾時、S3 上傳失敗、PG COPY 失敗",
    "sla": "須在 04:00 前完成",
    "crossCloud": false
  },
  {
    "id": "email_alert_list",
    "summary": "等 Entity Insight 資料搬完，再產生 email 警報寄送清單。",
    "schedule": "03:00 daily",
    "owner": "Vance",
    "stability": "retries=1, delay=5min",
    "source": "",
    "target": "Savvy PostgreSQL",
    "delay": "T+1",
    "description": "做的事：\n1. 等 entity_insight_migration 全部完成\n2. 依序處理每張 alert 表，寫入 Savvy P",
    "mermaidChart": "graph TD\n  A[等 entity_insight_migration] --> B[依序處理 alert 表] --> C[寫入 Savvy PG]",
    "pbiImpact": "",
    "volume": "MB 級",
    "retention": "全量刷新",
    "pii": "含 email、entity_id",
    "audience": "Email Alert 系統",
    "dbCoupling": "⚠️ Savvy PG",
    "failureReasons": "上游 migration 延遲",
    "sla": "須在 04:30 前完成",
    "crossCloud": false
  },
  {
    "id": "email_alert_condition",
    "summary": "計算哪些 Entity 符合 email 警報條件。",
    "schedule": "00:30 daily",
    "owner": "Vance",
    "stability": "retries=1, delay=5min",
    "source": "",
    "target": "Redshift",
    "delay": "T+1",
    "description": "做的事：\n1. 依序處理每張條件表，結果寫入 Redshif",
    "mermaidChart": "graph TD\n  A[依序處理條件表] --> B[寫入 Redshift]",
    "pbiImpact": "",
    "volume": "MB 級",
    "retention": "每日刷新",
    "pii": "含 entity_id",
    "audience": "email_alert_list 使用",
    "dbCoupling": "無（RS 內部）",
    "failureReasons": "RS 查詢逾時",
    "sla": "須在 01:00 前完成",
    "crossCloud": false
  },
  {
    "id": "Sales_Benchmark_ETL",
    "summary": "計算各 Entity 的銷售排名和 Benchmark。",
    "schedule": "01:00 daily",
    "owner": "Shan",
    "stability": "retries=2, delay=120min",
    "source": "",
    "target": "Redshift",
    "delay": "T+1",
    "description": "做的事（依序）：\n1. 更新銷售清單\n2. 同步 Entity 最新狀態\n3. 跑 Benchmark 排名計",
    "mermaidChart": "graph TD\n  A[更新銷售清單] --> B[同步 Entity 狀態] --> C[Benchmark 排名計算]",
    "pbiImpact": "",
    "volume": "MB 級",
    "retention": "全量刷新",
    "pii": "含 entity_id",
    "audience": "Power BI 8 報表",
    "dbCoupling": "⚠️ Product PG + Salesforce",
    "failureReasons": "PG 不穩、Salesforce 限流",
    "sla": "須在 02:00 前完成",
    "crossCloud": false
  },
  {
    "id": "target_audience_tags",
    "summary": "幫用戶打標籤、分群，給 email 行銷活動用。",
    "schedule": "12:00 weekly(Mon)",
    "owner": "Jackie",
    "stability": "retries=1, delay=2min",
    "source": "",
    "target": "Redshift",
    "delay": "T+1",
    "description": "做的事：\n1. 讀取 TAGS_TABLE_LIST 設定的表清單\n2. 依序對每張表執行 update_target_tags 腳",
    "mermaidChart": "graph TD\n  A[讀取表清單] --> B[依序更新標籤]",
    "pbiImpact": "",
    "volume": "MB 級",
    "retention": "每週刷新",
    "pii": "含 account_id、email",
    "audience": "Email Campaign Platform",
    "dbCoupling": "無（RS 內部）",
    "failureReasons": "RS 查詢逾時",
    "sla": "每週一下午前",
    "crossCloud": false
  },
  {
    "id": "user_tag_v11",
    "summary": "幫用戶打 v1.1 版標籤（職業、使用行為等）。",
    "schedule": "00:50 weekly(Mon)",
    "owner": "Vance",
    "stability": "retries=1, delay=5min",
    "source": "",
    "target": "Redshift",
    "delay": "T+1",
    "description": "做的事：\n1. 跑 user_tag_v11_preprocess（前處理）\n2. 如果是每月第 1～7 天，額外跑 user_tag_v11_aggregation（月度彙整",
    "mermaidChart": "graph TD\n  A[前處理] --> B{月初1-7日?}\n  B -->|Yes| C[月度彙整]\n  B -->|No| D[結束]",
    "pbiImpact": "",
    "volume": "MB 級",
    "retention": "每週+每月",
    "pii": "含 account_id",
    "audience": "Power BI（User Tag）",
    "dbCoupling": "無（RS 內部）",
    "failureReasons": "RS 查詢逾時",
    "sla": "每週一上午前",
    "crossCloud": false
  },
  {
    "id": "active_canvas_hour",
    "summary": "算上個月每個 App 的 Canvas 使用時數（月報用）。",
    "schedule": "04:30 monthly(1st)",
    "owner": "Jackie",
    "stability": "retries=2, delay=60s",
    "source": "",
    "target": "Redshift",
    "delay": "T+1",
    "description": "做的事（依序）：\n1. mvbA 的月度 Canvas Hour\n2. mvbW 的月度 Canvas Hour\n3. mvbF 的月度 Canvas Hou",
    "mermaidChart": "graph TD\n  A[mvbA Canvas Hour] --> B[mvbW Canvas Hour] --> C[mvbF Canvas Hour]",
    "pbiImpact": "",
    "volume": "MB 級",
    "retention": "每月追加",
    "pii": "無",
    "audience": "Power BI（Active Canvas Hour）",
    "dbCoupling": "無（RS 內部）",
    "failureReasons": "RS 查詢逾時",
    "sla": "每月 1 號 05:00 前",
    "crossCloud": false
  },
  {
    "id": "pbi_activity",
    "summary": "從 Power BI API 抓昨天的報表使用紀錄，存到 Redshift。",
    "schedule": "04:00 daily",
    "owner": "Jackie",
    "stability": "retries=1, delay=5min",
    "source": "Azure Power BI Admin API",
    "target": "S3 → Redshift",
    "delay": "T+1",
    "description": "做的事：\n1. 用 Azure OAuth 拿 token\n2. 同時抓 5 種活動：ExportReport、ActivityEvents、Artifact、Dataflow、Tile\n3. 合併後刪掉 Redshift 昨天的資料，再插入新",
    "mermaidChart": "graph TD\n  A[拿 Azure token] --> B[ExportReport]\n  A --> C[ActivityEvents]\n  A --> D[ExportArtifact]\n  A --> E[ExportDataflow]\n  A --> F[ExportTile]\n  B --> G[合併寫入 Redshift]\n  C --> G\n  D --> G\n  E --> G\n  F --> G",
    "pbiImpact": "",
    "volume": "MB 級",
    "retention": "每日追加",
    "pii": "含 UserId、ClientIP",
    "audience": "內部（追蹤 PBI 使用）",
    "dbCoupling": "Azure PBI Admin API",
    "failureReasons": "Azure token 過期、rate limit",
    "sla": "須在 05:00 前完成",
    "crossCloud": true
  },
  {
    "id": "daily_common_data_update",
    "summary": "更新國家、地區、城市的對照表。",
    "schedule": "00:20 daily",
    "owner": "Shan",
    "stability": "retries=3, delay=5min",
    "source": "Product PG（country, region, city）",
    "target": "S3 → Redshift",
    "delay": "T+1",
    "description": "做的事（依序）：\n1. 更新 country/region/city 對照\n2. 更新內部 Entity 清",
    "mermaidChart": "graph TD\n  A[更新國家/地區/城市對照] --> B[更新內部 Entity 清單]",
    "pbiImpact": "",
    "volume": "KB 級",
    "retention": "全量刷新",
    "pii": "無",
    "audience": "被其他 DAG/PBI 間接使用",
    "dbCoupling": "⚠️ Product PG",
    "failureReasons": "PG 連線不穩",
    "sla": "無嚴格 SLA",
    "crossCloud": false
  },
  {
    "id": "daily_viewsonic_dataset_update",
    "summary": "更新 ViewSonic 員工帳號和 Entity 資料。",
    "schedule": "00:20 daily",
    "owner": "Shan",
    "stability": "retries=3, delay=5min",
    "source": "Product PG（vs_employee, account_entity）",
    "target": "S3 → Redshift",
    "delay": "T+1",
    "description": "做的事（依序）：\n1. 更新 ViewSonic Entity\n2. 更新 ViewSonic 帳號\n3. 更新 Savvy demo ID\n4. 更新 daco account I",
    "mermaidChart": "graph TD\n  A[更新 VS Entity] --> B[更新 VS 帳號] --> C[更新 Savvy demo ID] --> D[更新 daco account ID]",
    "pbiImpact": "",
    "volume": "KB 級",
    "retention": "全量刷新",
    "pii": "含 VS 員工帳號",
    "audience": "內部篩選用",
    "dbCoupling": "⚠️ Product PG",
    "failureReasons": "PG 連線不穩",
    "sla": "無嚴格 SLA",
    "crossCloud": false
  },
  {
    "id": "msp",
    "summary": "抓 MSP（管理服務商）的帳號、Entity、管理對象資料。",
    "schedule": "00:00 daily",
    "owner": "Penny",
    "stability": "retries=1, delay=1min",
    "source": "Product PG（entity_requirement, msp_managed）",
    "target": "S3 → Redshift",
    "delay": "T+1",
    "description": "做的事（依序）：\n1. account_msp（MSP 帳號）\n2. entity_account_msp（MSP Entity 帳號對應）\n3. entity_msp_managed（MSP 管理的 Entity）\n4. entity_requirement_msp（MSP 需求",
    "mermaidChart": "graph TD\n  A[account_msp] --> B[entity_account_msp] --> C[entity_msp_managed] --> D[entity_requirement_msp]",
    "pbiImpact": "",
    "volume": "MB 級",
    "retention": "全量刷新",
    "pii": "含 entity_id、account_id",
    "audience": "Power BI（MSP 系列）",
    "dbCoupling": "⚠️ Product PG",
    "failureReasons": "PG 連線不穩",
    "sla": "無嚴格 SLA",
    "crossCloud": false
  },
  {
    "id": "email_log",
    "summary": "從產品 DB 抓系統寄出的 email 記錄。",
    "schedule": "02:00 daily",
    "owner": "Jackie",
    "stability": "retries=3, delay=1min",
    "source": "Product PG（system_email_log）",
    "target": "S3 → Redshift",
    "delay": "T+1",
    "description": "做的事：\n1. 依序處理 EMAIL_LOG_LIST 裡的每張",
    "mermaidChart": "graph TD\n  A[依序處理 email log 表] --> B[寫入 Redshift]",
    "pbiImpact": "",
    "volume": "MB 級",
    "retention": "每日追加",
    "pii": "⚠️ 含 email、account_id",
    "audience": "內部分析",
    "dbCoupling": "⚠️ Product PG",
    "failureReasons": "PG 連線不穩",
    "sla": "無嚴格 SLA",
    "crossCloud": false
  },
  {
    "id": "oracle_ifp",
    "summary": "把 Oracle IFP 硬體銷售資料從 S3 寫進 Redshift。",
    "schedule": "00:30 daily",
    "owner": "Jackie",
    "stability": "retries=3, delay=5min",
    "source": "S3（Oracle IFP 銷售資料）",
    "target": "Redshift",
    "delay": "T+1",
    "description": "做的事（單一步驟）：\n1. 讀 S3 上的 Oracle 資料，寫入 Redshif",
    "mermaidChart": "graph TD\n  A[讀 S3 Oracle 資料] --> B[寫入 Redshift]",
    "pbiImpact": "",
    "volume": "MB 級",
    "retention": "全量刷新",
    "pii": "含 serial_number",
    "audience": "Power BI（IFP Activity）",
    "dbCoupling": "S3 Oracle 匯出檔",
    "failureReasons": "Oracle 檔案格式變更",
    "sla": "須在 01:00 前完成",
    "crossCloud": false
  },
  {
    "id": "originals_recommend",
    "summary": "每月重新計算 OC 推薦清單。",
    "schedule": "03:30 monthly(1st)",
    "owner": "Jackie",
    "stability": "retries=1",
    "source": "",
    "target": "DynamoDB",
    "delay": "T+1",
    "description": "做的事（依序）：\n1. 更新 subject 對照表\n2. 跑 v2 推薦演算法，結果寫入 DynamoD",
    "mermaidChart": "graph TD\n  A[更新 subject 對照表] --> B[v2 推薦演算法] --> C[寫入 DynamoDB]",
    "pbiImpact": "",
    "volume": "MB 級",
    "retention": "每月全量刷新",
    "pii": "含 content_id",
    "audience": "產品端（App 推薦列表）",
    "dbCoupling": "DynamoDB",
    "failureReasons": "推薦演算法失敗",
    "sla": "每月 1 號完成",
    "crossCloud": false
  },
  {
    "id": "originals_ai_tags",
    "summary": "用 Google Gemini AI 幫 OC 資源自動打標籤。",
    "schedule": "04:00 daily",
    "owner": "Jackie",
    "stability": "retries=3, delay=5min",
    "source": "",
    "target": "S3",
    "delay": "T+1",
    "description": "做的事（依序）：\n1. 掃描 S3 上的 resource 檔案，用 Gemini 產生標籤\n2. 掃描 background 檔案，用 Gemini 產生標",
    "mermaidChart": "graph TD\n  A[Gemini 標籤 resource] --> B[Gemini 標籤 background]",
    "pbiImpact": "",
    "volume": "MB 級",
    "retention": "累積",
    "pii": "無",
    "audience": "產品端（OC 自動標籤）",
    "dbCoupling": "Google Gemini API",
    "failureReasons": "Gemini API 限流、S3 失敗",
    "sla": "須在 05:00 前完成",
    "crossCloud": false
  },
  {
    "id": "oc_modified_daily_monitor",
    "summary": "監控 OC S3 bucket 有沒有被異動，有的話寄 email 通知。",
    "schedule": "—",
    "owner": "—",
    "stability": "—",
    "source": "—",
    "target": "—",
    "delay": "T+1",
    "description": "",
    "mermaidChart": "graph TD\n  A[掃描 OC S3 bucket] --> B{有異動?}\n  B -->|Yes| C[寄 email 通知]\n  B -->|No| D[結束]",
    "pbiImpact": "",
    "volume": "KB 級",
    "retention": "無產出",
    "pii": "無",
    "audience": "OC team（email 通知）",
    "dbCoupling": "無",
    "failureReasons": "S3 權限變更",
    "sla": "無",
    "crossCloud": false
  },
  {
    "id": "event_tool_map",
    "summary": "更新 Redshift 裡的工具名稱對照表。",
    "schedule": "—",
    "owner": "—",
    "stability": "—",
    "source": "—",
    "target": "—",
    "delay": "T+1",
    "description": "做的事：把 CSV 裡的 event category、event change、tool map、feature label、event type mapping 寫入 Redshift",
    "mermaidChart": "graph TD\n  A[讀取 CSV 對照表] --> B[寫入 Redshift]",
    "pbiImpact": "",
    "volume": "KB 級",
    "retention": "全量刷新",
    "pii": "無",
    "audience": "Redshift（JOIN 用）",
    "dbCoupling": "無",
    "failureReasons": "CSV 格式變更",
    "sla": "每月完成",
    "crossCloud": false
  },
  {
    "id": "entity_insight_stage_migration",
    "summary": "跟 entity_insight_migration 一樣，但是跑在 Stage 環境（測試用）。",
    "schedule": "—",
    "owner": "—",
    "stability": "—",
    "source": "—",
    "target": "—",
    "delay": "T+1",
    "description": "",
    "mermaidChart": "graph TD\n  A[Stage 版 entity_insight_migration] --> B[29 張表循序處理]",
    "pbiImpact": "",
    "volume": "GB 級",
    "retention": "同 prod",
    "pii": "同 prod",
    "audience": "Stage 測試",
    "dbCoupling": "Stage Savvy PG",
    "failureReasons": "同 prod",
    "sla": "無",
    "crossCloud": false
  },
  {
    "id": "manual_rerun",
    "summary": "工具人 DAG，可以手動指定要重跑哪支程式、哪個日期範圍。",
    "schedule": "—",
    "owner": "—",
    "stability": "—",
    "source": "—",
    "target": "—",
    "delay": "T+1",
    "description": "",
    "mermaidChart": "graph TD\n  A[指定 script + 日期] --> B[執行重跑]",
    "pbiImpact": "",
    "volume": "依參數",
    "retention": "依參數",
    "pii": "依參數",
    "audience": "手動維運",
    "dbCoupling": "依參數",
    "failureReasons": "參數錯誤",
    "sla": "無",
    "crossCloud": false
  },
  {
    "id": "dbt_demo_dag",
    "summary": "DBT 測試用 DAG，跑 device 相關的 demo model。",
    "schedule": "—",
    "owner": "—",
    "stability": "—",
    "source": "—",
    "target": "—",
    "delay": "T+1",
    "description": "",
    "mermaidChart": "graph TD\n  A[device_latest_info] --> B[device_first_last_actions] --> C[dm_info_all_time]",
    "pbiImpact": "",
    "volume": "MB 級",
    "retention": "測試用",
    "pii": "無",
    "audience": "開發測試",
    "dbCoupling": "無",
    "failureReasons": "dbt 語法錯誤",
    "sla": "無",
    "crossCloud": false
  }
];
